### ISSUE TITLE
Desenvolvimento do Banco de Dados

### ISSUE THREAD

**Issue by yullano90** [yullano90/emserf_service_map_manager#5]
- [x] Abstrair e criar tabelas conforme necessidade do cliente EMSERF.
- [x] Modelar o Banco de Dados.
- [x] Realizar Engenharia Reversa e gerar Diagrama ER.
- [x] Documentar o Banco de Dados.

**Comment by scjailson** [comment]
Banco de dados projetado, juntamente com o diagrama de relacionamento feito por engenharia reversa

**Comment by scjailson** [comment]
Banco de dados projetado, juntamente com o diagrama de relacionamento feito por engenharia reversa
